server:
  port: 8082

spring:
  application:
    name: delivery-service
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:postgresql://postgres-db:5432/quickfood_delivery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: VLOQmJ8TkXNXxN5b4cw2sjdRj4M0Amh1GjCNGZj59xLOvC1ojGUQnFcYbghvJgQRaFcYfHEqIyg8M1PZmr9A
