package com.quickfood.deliveryservice.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.util.List;

@Component
public class JwtUtil {

    private final SecretKey secretKey;

    public JwtUtil(@Value("${jwt.secret}") String secret) {
        // Must match API Gateway's JwtUtils — both use BASE64 decoding
        this.secretKey = Keys.hmacShaKeyFor(Decoders.BASE64.decode(secret));
    }

    public Claims parseToken(String token) {
        return Jwts.parser()
                .verifyWith(secretKey)
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    /**
     * JWT generated by core-service stores user ID in the "id" claim (Long).
     */
    public Long getUserId(Claims claims) {
        return claims.get("id", Long.class);
    }

    /**
     * JWT generated by core-service stores the role as a single string "role" claim.
     * Returns it as a single-element list to keep the filter generic.
     */
    public List<String> getRoles(Claims claims) {
        String role = claims.get("role", String.class);
        return role != null ? List.of(role) : List.of();
    }

    public boolean validateToken(String token) {
        try {
            parseToken(token);
            return true;
        } catch (JwtException | IllegalArgumentException e) {
            return false;
        }
    }
}
